modLoader="javafml"
loaderVersion="*"
issueTrackerURL="https://github.com/UltimatChamp/EnhancedTooltips/issues"
displayURL="https://github.com/UltimatChamp/EnhancedTooltips"
logoFile="assets/${mod_id}/icon.png"
authors="${mod_authors}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="optional"
versionRange="*"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="${mod_id}.mixins.json"
